DROP TABLE #fornecedores

SELECT 
	A2_COD,
	A2_TIPO,
	A2_CGC,
	A2_NOME,
	SUBSTRING(E2_FILIAL,0,3) AS FILIAL,
	A2_CALCIRF ,
	A2_IRPROG ,
	ISNULL(DKE_IRSIMP,'') AS IRSIMP,
	ROW_NUMBER() OVER(PARTITION BY A2_COD, A2_CGC ORDER BY A2_COD) AS IDENTT
	INTO #fornecedores
FROM SA2010 SA2 WITH(NOLOCK)
LEFT JOIN DKE010 DKE WITH(NOLOCK)
	ON DKE_COD = A2_COD
LEFT JOIN SE2010 SE2 WITH(NOLOCK)
	ON E2_FORNECE = A2_COD
WHERE A2_ZCODRET = 3208
	AND A2_TIPO = 'F'
	AND SA2.D_E_L_E_T_ = ''
ORDER BY E2_NUM DESC

	

	SELECT
		CASE 
			WHEN FILIAL = '90' THEN 'Cresol Confederação'
			WHEN FILIAL = '01' THEN 'Cresol Baser'
			WHEN FILIAL = '02' THEN 'Central Brasil'
			WHEN FILIAL = '05' THEN 'Central Cresol Sicoper'
			WHEN FILIAL = '04' THEN '[LIQUIDADA] Central Cresol Nordeste'
			ELSE FILIAL
		END AS FILIAL,
		A2_COD,
		A2_TIPO,
		A2_CGC,
		A2_NOME,
		CASE 
			WHEN A2_CALCIRF = 1 THEN 'Normal'
			WHEN A2_CALCIRF = 2 THEN 'IRRF Baixa'
			WHEN A2_CALCIRF = 3 THEN 'Simples'
			WHEN A2_CALCIRF = 4 THEN 'Empresa Individual'
			ELSE A2_CALCIRF 
		END AS A2_CALCIRF, --Cálc. IRRF
		CASE 
			WHEN A2_IRPROG = 1 THEN 'Sim'
			WHEN A2_IRPROG = 2 THEN 'Não'
			ELSE A2_IRPROG 
		END AS A2_IRPROG, -- IRRF Prog
		CASE 
			WHEN IRSIMP = 1 THEN 'Sim'
			WHEN IRSIMP = 2 THEN 'Não'
			ELSE IRSIMP -- IR Simp
		END AS IRSIMP
	FROM #fornecedores
	WHERE IDENTT = 1
	

