DROP TABLE #DADOS


SELECT 
	FK2_LA,
	FK5_LA,
	E2_LA,
	E5_LA,
	FK2.R_E_C_N_O_ AS FK2RECNO,
	FK5.R_E_C_N_O_ AS FK5RECNO,
	SE2.R_E_C_N_O_ AS SE2RECNO,
	SE5.R_E_C_N_O_ AS SE5RECNO,
	FK2_VALOR,
	SE2.E2_VALOR
	FK2_DOC,
	SE2.E2_EMISSAO,
	E2_VENCTO,
	E2_NUM,
	E2_FILIAL,
	E2_NUMBOR,
	GETDATE() AS hora
	INTO #DADOS
FROM SE2010 SE2 WITH(NOLOCK)
INNER JOIN FK7010 FK7 WITH(NOLOCK)
	ON E2_FILIAL = FK7_FILTIT 
	AND E2_PREFIXO = FK7_PREFIX 
	AND E2_NUM = FK7_NUM 
	AND E2_PARCELA = FK7_PARCEL 
	AND E2_TIPO = FK7_TIPO 
	AND E2_FORNECE = FK7_CLIFOR 
	AND E2_LOJA = FK7_LOJA
INNER JOIN FK2010 FK2 WITH(NOLOCK)
	ON FK7_IDDOC = FK2_IDDOC
INNER JOIN FK5010 FK5 WITH(NOLOCK)
	ON FK5_IDFK7 = FK7_IDDOC
INNER JOIN SE5010 SE5 WITH(NOLOCK)
	ON E5_PREFIXO = E2_PREFIXO  AND E5_NUMERO = E2_NUM AND E5_PARCELA = E2_PARCELA  AND E5_TIPO = E2_TIPO  AND E5_FORNECE = E2_FORNECE  AND E5_LOJA = E2_LOJA
WHERE E2_FILIAL between 016900 AND 016999 AND E2_NUM IN ('001640667','000147685')



SELECT 
	* 
FROM #DADOS


-----------------------------------------

/*

UPDATE FK2010
SET FK2_LA = 'N'
FROM #DADOS
WHERE R_E_C_N_O_ = FK2RECNO




UPDATE FK5010
SET FK5_LA = 'N'
FROM #DADOS
WHERE R_E_C_N_O_ = FK5RECNO




UPDATE SE2010
SET E2_LA = 'N'
FROM #DADOS
WHERE R_E_C_N_O_ = SE2RECNO




UPDATE SE5010
SET E5_LA = ''
FROM #DADOS
WHERE R_E_C_N_O_ = SE5RECNO

*/


DECLARE @recnoCTK AS INT
DECLARE @filial AS INT = 014999
DECLARE @titulo AS VARCHAR(20) = '000098859' 
DECLARE @lancamento AS VARCHAR(10) = 'S'

IF @lancamento = 'S'
BEGIN
	SELECT 
		CASE
			WHEN EXISTS(
				SELECT 1
				FROM CT2010 CT2 WITH(NOLOCK)
				WHERE CT2.R_E_C_N_O_ = CV3_RECDES
					AND CT2_AT03DB = @titulo
					AND CT2_FILIAL = @filial
					AND D_E_L_E_T_ = ''
			) THEN 'Existe lançamento contábil'
			ELSE 'Não existe lançamento'
		END AS ExisteLancamento,
		CV3_FILIAL,
		CV3_KEY,
		CV3_DEBITO,
		CV3_CREDIT,
		CV3_VLR01,
		CV3_HIST,
		COUNT(*) AS NmrLinha
	FROM CV3010 CV3 WITH(NOLOCK)
	INNER JOIN CTK010 CTK WITH(NOLOCK)
		ON CTK_KEY = CV3_KEY
		AND CTK.D_E_L_E_T_ = ''
		AND CTK_AT03DB = @titulo
		AND CTK_FILIAL = @filial
	WHERE CV3.D_E_L_E_T_ = ''
		--AND CV3_RECDES <> ''
	GROUP BY CV3_FILIAL, CV3_KEY, CV3_DEBITO, CV3_CREDIT, CV3_VLR01, CV3_HIST, CV3_RECDES
END
ELSE IF @lancamento = '2'
BEGIN
	SELECT 
		*
	FROM CT2010 WITH(NOLOCK)
	WHERE CT2_FILIAL = @filial
		AND CT2_AT03DB = @titulo
		
	SELECT 
		CV3_AT02DB,
		CV3_AT03CR,
		*
	from CV3010 WITH(NOLOCK)
	WHERE CV3_FILIAL = @filial
		AND CV3_AT03DB = @titulo
END
ELSE IF @lancamento = 'CTK'
BEGIN
	SELECT 
		*
	FROM CTK010 WITH(NOLOCK)
	WHERE CTK_AT03DB = @titulo
		AND CTK_FILIAL = @filial
		AND D_E_L_E_T_ = ''
END
ELSE
BEGIN
	SELECT 
		'Valor inválido da Variável declarada' AS ops
END	



