DECLARE @nome AS VARCHAR(100)
DECLARE @valor AS float
DECLARE @filial AS INT
DECLARE @se2Recno AS INT
DECLARE @data AS INT = 20250401
DECLARE @idrel AS VARCHAR(100) = '19582'


SELECT
	@valor = SUM(ZZ8_VALOR),
	@filial = ZZ8_XFIL,
	@nome = '%' + SUBSTRING(TRIM(A2_NOME),0,20) + '%'
FROM ZZ8010 WITH(NOLOCK)
INNER JOIN SA2010 WITH(NOLOCK)
	ON ZZ8_CGC = A2_CGC
WHERE ZZ8_IDREL = @idrel
GROUP BY ZZ8_XFIL, A2_NOME



SELECT
	@se2Recno = R_E_C_N_O_
FROM SE2010 WITH(NOLOCK)
WHERE E2_EMISSAO > @data
	AND E2_NOMFOR LIKE @nome
	AND E2_FILIAL = @filial
	AND E2_VALOR = @valor     



IF ISNULL(@se2Recno,'') = ''
BEGIN
	SELECT 'Nao atualizou' as ATUALIZADO
END
ELSE 
BEGIN
	UPDATE ZZ8010
	SET ZZ8_RECSE2 = @se2Recno
	WHERE ZZ8_IDREL = @idrel


	SELECT 
		'Atualizou' as ATUALIZADO,
		*
	FROM SE2010 WITH(NOLOCK)
	WHERE R_E_C_N_O_ = @se2Recno
END

