SELECT
	FIL.USR_ID,
	USR_CODIGO,
	USR_NOME,
	CASE 
		WHEN USR_CODEMP = '90' THEN 'Confederação'
		WHEN USR_CODEMP = '01' THEN 'Central Baser'
		WHEN USR_CODEMP = '02' then 'Central Brasil'
		WHEN USR_CODEMP = '04' THEN '[LIQUIDADA] Central Nordeste'
		WHEN USR_CODEMP = '05' THEN 'Central Sicoper'
		ELSE USR_CODEMP
	END AS ACESSOEMPRESA,
	CASE 
		WHEN USR_FILIAL = '' AND USR_CODUNG <> '' THEN TRIM(USR_CODEMP) + TRIM(USR_CODUNG)
		WHEN USR_CODUNG = '' THEN CAST(TRIM(USR_CODEMP)AS VARCHAR(10)) + '00'
		ELSE USR_FILIAL
	END AS FILIAIS,
	USR_CARGO
FROM (
	SELECT  
		USR.USR_ID,
		USR.USR_CODIGO,
		USR.USR_NOME,
		USR.USR_DEPTO,
		USR.USR_CARGO,
		ROW_NUMBER() OVER(PARTITION BY USR_ID, USR_CODIGO, USR_EMAIL, USR_DEPTO, USR_NOME ORDER BY USR_CODIGO) AS LINHAD
	FROM dbo.SYS_USR USR WITH(NOLOCK)
	WHERE USR.D_E_L_E_T_ = ''
) AS USR
INNER JOIN SYS_USR_FILIAL FIL WITH(NOLOCK)
	ON FIL.USR_ID = USR.USR_ID
WHERE  FIL.D_E_L_E_T_ = ''
	AND LINHAD = 1

